env:
  node: true
  es6: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'next/core-web-vitals'
  - 'prettier'

plugins:
  - 'unused-imports'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.eslint.json

rules:
  import/order:
    - error
    - alphabetize:
        order: 'asc'
  '@typescript-eslint/consistent-type-imports': error
  react/jsx-key:
    - error
    - checkFragmentShorthand: true
      warnOnDuplicates: true

settings:
  import/resolver: typescript
