name: 'ci'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '^14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint
